version: 2
updates:

  # Enable version updates for GitHub Actions workflows
  - package-ecosystem: "github-actions"
    # Look for workflow files in the .github/workflows directory (or root if they are there)
    directory: "/"
    # Check for updates weekly
    schedule:
      interval: "weekly"
