codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
    
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false

ignore:
  - "test-*.ts"
  - "**/*.config.ts"
  - "**/*.d.ts"
  - ".cursor/**"
  - ".github/**"
  - "dist/**"
  - "node_modules/**"

