version: '3.8'

services:
  mariadb:
    image: mariadb:11.8
    container_name: finx-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-finx_root_password}
      MYSQL_DATABASE: ${DB_NAME:-finx}
      MYSQL_USER: ${DB_USER:-finx_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-finx_password}
      TZ: UTC
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d:ro
      - ./database/migrations:/migrations:ro
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max-connections=200
      --innodb-buffer-pool-size=256M
      --innodb-log-file-size=64M
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - finx-network

volumes:
  mariadb_data:
    driver: local
    name: finx-mariadb-data

networks:
  finx-network:
    driver: bridge
    name: finx-network

